components:

  - name: ingress-nginx
    version: 1.0.0
    config:
      timeout: 1m
      install:
        createNamespace: true
    source:
      defaultVersion: 4.10.0
      allowedVersions:
        - 4.10.0
        - 4.11.3
      helmRepository:
        url: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
    roles:
      - ingress
    parameters:
      mode: # metallb, hostPort, nodePort
      endpoint: # TBD is metallb
    values: |
      controller:
        allowSnippetAnnotations: "true"
        extraArgs:
          enable-ssl-passthrough: true
      {{- if eq .Parameters.mode "metallb" }}
        service:
          annotations:
            metallb.universe.tf/loadBalancerIPs: {{ resolveDNS .Parameters.endpoint }}
            metallb.universe.tf/allow-shared-ip: "ingress"
      {{- end }}
      {{- if eq .Parameters.mode "hostPort" }}
        hostNetwork: true
        hostPort:
          enabled: true
        service:
          enabled: false      
      {{- end }}
      {{- if eq .Parameters.mode "nodePort" }}
        service:
          type: NodePort
          nodePorts:
            http: "30080"
            https: "30443"      
      {{- end }}
